version: '3'
services:
  frontend:
    build: ./fe
    ports: 
      - "3000:3000"
  
  nginx:
    image: nginx
    volumes:
     - ./templates:/etc/nginx/templates
    ports:
     - "8080:80"
    depends_on:
      - frontend
    env_file: 
      - .env
